# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.10.0

    working_directory: ~/compose

    steps:
      - checkout
      - run: npm install
      - run: npm run test:ci
      - run: npm i -D coveralls codecov
      - run: npx coveralls
      - run: npx codecov
